---
  kind: pipeline
  type: docker
  name: default

  steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: r.j5y.xyz/delta
      registry: r.j5y.xyz
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      auto_tag: true
      debug: true
      tags:
        - latest
        - ${DRONE_BUILD_NUMBER}
        - ${DRONE_COMMIT_SHA:0:8}
    when:
      branch: master

